# Generated by Django 5.2.5 on 2025-08-20 21:05

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название зала"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание зала"),
                ),
                (
                    "width",
                    models.PositiveSmallIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="Ширина зала (столики)",
                    ),
                ),
                (
                    "height",
                    models.PositiveSmallIntegerField(
                        default=8,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="Длина зала (столики)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Зал ресторана",
                "verbose_name_plural": "Залы ресторана",
            },
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=10, verbose_name="Номер столика"),
                ),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="Вместимость",
                    ),
                ),
                (
                    "x_position",
                    models.PositiveSmallIntegerField(verbose_name="Позиция X"),
                ),
                (
                    "y_position",
                    models.PositiveSmallIntegerField(verbose_name="Позиция Y"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Доступен для брони"
                    ),
                ),
                (
                    "hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="reservation.hall",
                        verbose_name="Зал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Столик",
                "verbose_name_plural": "Столики",
                "ordering": ["hall", "number"],
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата бронирования")),
                ("start_time", models.TimeField(verbose_name="Время начала")),
                (
                    "duration",
                    models.DurationField(
                        default=datetime.timedelta(seconds=7200),
                        help_text="По умолчанию 2 часа. Меняется только админом",
                        verbose_name="Длительность брони",
                    ),
                ),
                (
                    "guests_count",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Количество гостей",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Подтверждено"),
                            ("canceled", "Отменено"),
                            ("completed", "Завершено"),
                        ],
                        default="confirmed",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "event",
                    models.TextField(
                        blank=True,
                        help_text="Планируется ли какое-то событие? Например, день рождения.",
                        null=True,
                        verbose_name="Событие",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "extended_by_admin",
                    models.BooleanField(default=False, verbose_name="Продлена вручную"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("guest", "Гость через сайт"),
                            ("admin", "Администратор вручную"),
                        ],
                        default="guest",
                        help_text="Кем оформлена бронь (определяется автоматически)",
                        max_length=20,
                        verbose_name="Источник брони",
                    ),
                ),
                (
                    "staff_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Если бронь оформлялась персоналом",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_reservations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Менеджер/админ",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservation.table",
                        verbose_name="Столик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронь",
                "verbose_name_plural": "Брони",
                "ordering": ["-date", "-start_time"],
            },
        ),
        migrations.AddConstraint(
            model_name="table",
            constraint=models.UniqueConstraint(
                fields=("hall", "x_position", "y_position"),
                name="unique_table_position",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="table",
            unique_together={("hall", "number")},
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.UniqueConstraint(
                fields=("table", "date", "start_time"), name="unique_reservation"
            ),
        ),
    ]
