# Generated by Django 4.2.2 on 2025-08-25 09:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="duration",
            field=models.DurationField(
                default=datetime.timedelta(seconds=10800),
                help_text="По умолчанию 3 часа. Меняется только админом",
                verbose_name="Длительность брони",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="guests_count",
            field=models.PositiveSmallIntegerField(verbose_name="Количество гостей"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guest_reservations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
