# Generated by Django 4.2.2 on 2025-08-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0002_alter_reservation_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hall",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/halls/",
                verbose_name="Изображение зала",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="source",
            field=models.CharField(
                choices=[
                    ("guest", "Гость через сайт"),
                    ("admin", "Администратор вручную"),
                ],
                default="guest",
                help_text="Кем оформлена бронь",
                max_length=20,
                verbose_name="Источник брони",
            ),
        ),
    ]
