# Generated by Django 4.2.2 on 2025-08-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0003_hall_image_alter_reservation_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hall",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="halls/",
                verbose_name="Изображение зала",
            ),
        ),
    ]
