# Generated by Django 4.2.2 on 2025-08-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0004_alter_hall_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает подтверждения"),
                    ("confirmed", "Подтверждено"),
                    ("canceled", "Отменено"),
                    ("completed", "Завершено"),
                ],
                default="confirmed",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
